orders_articles_analyze_table = {
    "title": "orders_articles_analyze",
    "columns": {'date' : 'date', 
                'week_num' : 'int8', 
                'month_num' : 'int8',     
                'account' : 'VARCHAR(255)', 
                'local_vendor_code' : 'VARCHAR(255)',
                'article_id' : 'NUMERIC(20,0) ', 
                'subject_name' : 'VARCHAR(255)', 
                'price_with_disc' : 'NUMERIC(15, 2)', 
                'spp' : 'int8',
                'orders_sum_rub' : 'NUMERIC(15, 2)', 
                'orders_count' : 'int8', 
                'profit_by_orders' : 'NUMERIC(15, 2)',
                'profit_by_cond_orders' : 'NUMERIC(15, 2)',
                'sales_sum' : 'NUMERIC(15, 2)', 
                'sales_count' : 'int8',
                'profit_by_cond_sales' : 'NUMERIC(15, 2)',
                'open_card_count' : 'int8', 
                'add_to_cart_count' : 'int8',
                'to_cart_convers' : 'NUMERIC(15, 2)',
                'to_orders_convers' : 'NUMERIC(15, 2)', 
                'manager' : 'VARCHAR(255)', 
                'promo_title' : 'VARCHAR(255)', 
                'promo_status' : 'VARCHAR(255',
                'central' : 'NUMERIC(15, 2)', 
                'south' : 'NUMERIC(15, 2)', 
                'privolzhskiy' : 'NUMERIC(15, 2)', 
                'north_caucase' : 'NUMERIC(15, 2)',
                'total_quantity' : 'int8', 
                'central_fo_orders' : 'int8', 
                'south_fo_orders' : 'int8',
                'privolzhskiy_fo_orders' : 'int8', 
                'north_caucase_fo_orders' : 'int8', 
                'far_eastern_fo_orders' : 'int8',
                'ural_fo_orders' : 'int8', 
                'north_west_fo_orders' : 'int8', 
                'syberian_fo_orders' : 'int8', 
                'purchase_price' : 'NUMERIC(15, 2)',
                'kgvp_marketplace' : 'NUMERIC(15, 2)', 
                'ind_comission' : 'int8', 
                'logistic_from_wb_wh_to_opp' : 'NUMERIC(15, 2)', 
                'fbs_orders' : 'int8',
                'fbo_orders' : 'int8', 
                'stock_fbs' : 'int8', 
                'procurement_status' : 'VARCHAR(255)', 
                'parent_name' : 'VARCHAR(255)',
                'clicks' : 'int8', 
                'views' : 'int8', 
                'ctr' : 'NUMERIC(15, 2)', 
                'cpc' : 'NUMERIC(15, 2)', 
                'cpm' : 'NUMERIC(15, 2)', 
                'adv_spend' : 'NUMERIC(15, 2)', 
                'bonuses' : 'NUMERIC(15, 2)', 
                'rating' : 'NUMERIC(15, 2)',
                'price_with_disc_median_for_30days' : 'NUMERIC(15, 2)', 'price_with_disc_av_for_30days' : 'NUMERIC(15, 2)', 'orders_count_sum_for_30days' : 'NUMERIC(15, 2)',
                'orders_count_av_for_30days' : 'NUMERIC(15, 2)', 'orders_sum_rub_sum_for_30days' : 'NUMERIC(15, 2)', 'orders_sum_rub_av_for_30days' : 'NUMERIC(15, 2)',
                'end_of_day_balance': 'int8',
                'in_way_to_client' : 'int8', 
                'in_way_from_client' : 'int8'},
    "unique_keys" : ["date", "article_id"]
}