services:
  payments-analytics-api:
    build:
      context: ../..
      dockerfile: apps/payments_analytics_api/Dockerfile
    container_name: payments-analytics-api
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ../../:/app/project
    restart: unless-stopped
