from sqlalchemy import Date, String, BigInteger, Numeric

# Колонки Артикульного анализа
orders_articles_analyze_table = {
    "title": "orders_articles_analyze",
    "columns": {
        'date': Date,
        'week_num': BigInteger,
        'month_num': BigInteger,
        'account': String(255),
        'local_vendor_code': String(255),
        'article_id': Numeric(20, 0),
        'subject_name': String(255),
        'price_with_disc': Numeric(15, 2),
        'spp': BigInteger,
        'orders_sum_rub': Numeric(15, 2),
        'orders_count': BigInteger,
        'profit_by_orders': Numeric(15, 2),
        'profit_by_cond_orders': Numeric(15, 2),
        'sales_sum': Numeric(15, 2),
        'sales_count': BigInteger,
        'profit_by_cond_sales': Numeric(15, 2),
        'open_card_count': BigInteger,
        'add_to_cart_count': BigInteger,
        'to_cart_convers': Numeric(15, 2),
        'to_orders_convers': Numeric(15, 2),
        'manager': String(255),
        'promo_title': String(255),
        'promo_status': String(255),
        'central': Numeric(15, 2),
        'south': Numeric(15, 2),
        'privolzhskiy': Numeric(15, 2),
        'north_caucase': Numeric(15, 2),
        'total_quantity': BigInteger,
        'central_fo_orders': BigInteger,
        'south_fo_orders': BigInteger,
        'privolzhskiy_fo_orders': BigInteger,
        'north_caucase_fo_orders': BigInteger,
        'far_eastern_fo_orders': BigInteger,
        'ural_fo_orders': BigInteger,
        'north_west_fo_orders': BigInteger,
        'syberian_fo_orders': BigInteger,
        'purchase_price': Numeric(15, 2),
        'kgvp_marketplace': Numeric(15, 2),
        'ind_comission_fbo': BigInteger,
        'logistic_from_wb_wh_to_opp': Numeric(15, 2),
        'fbs_orders': BigInteger,
        'fbo_orders': BigInteger,
        'clicks': BigInteger,
        'views': BigInteger,
        'ctr': Numeric(15, 2),
        'cpc': Numeric(15, 2),
        'cpm': Numeric(15, 2),
        'adv_spend': Numeric(15, 2),
        'bonuses': Numeric(15, 2),
        'rating': Numeric(15, 2),
        'end_of_day_balance': BigInteger,
        'in_way_to_client': BigInteger,
        'in_way_from_client': BigInteger,
        'sales_revenue_rep': Numeric(15, 2),
        'sales_profit_cond_rep': Numeric(10, 2),
        'wb_commission_rep': Numeric(10, 2),
        'logistics': Numeric(10, 2),
        'sales_count_rep': BigInteger,
        'returns_count_rep': BigInteger,
        'cost_price_sales_fin_rep': Numeric(10, 2)
    },
    "unique_keys": ["date", "article_id"]
    }