from src_oop.jobs.fbo_supplies.config import (
    FBO_SUPPLIES_COLUMN_MAPPING,
    FBO_SUPPLIES_COLUMNS,
    FBO_SUPPLIES_ORDERS_BY_REGION_QUERY,
    SHIPMENTS_FBO_TABLE,
)

# Совместимость на переходный период: старые имена указывают на новую конфигурацию.
shipments_fbo = SHIPMENTS_FBO_TABLE
LOGISTIC_VED_COLUMNS = FBO_SUPPLIES_COLUMNS
LOGISTIC_VED_COLUMN_MAPPING = FBO_SUPPLIES_COLUMN_MAPPING
LOGISTIC_VED_ORDERS_BY_REGION_QUERY = FBO_SUPPLIES_ORDERS_BY_REGION_QUERY
